### ISSUE TITLE
Can we set timeout ??

### ISSUE THREAD

**Issue by rootxad** [CodeingBoy/GDIndex#11]
Hey:

can we set timeout for the request file such as setTimeout(request, 10000);

After 10 second file starts to download but in back the file url is ready to download just becuase of timeout its paused.

Cloud flare doesn't handle timeout, it throws error but it says it can be done during request handling ??

This is not a useful function which can be added in public source but its a small change can we done directly.

Thanks for the support for Export URL and Aria2 and also @maple3142

**Comment by maple3142** [comment]
??

**Comment by rootxad** [comment]
I tagged you for the thanks, sorry for the misunderstanding.

Well, you have come along can you suggest what trick can do the setTimeout thing ??

**Comment by rootxad** [comment]
I guess custom requests are not allowed.
