### ISSUE TITLE
Adblocker Detection & Header Text

### ISSUE THREAD

**Issue by Ex-Communicad0** [CodeingBoy/GDIndex#8]
Hello, can you put this funtion on this script

https://www.jqueryscript.net/other/jQuery-Plugin-For-AdBlock-Detection-Adi-js.html

And can you tell me how to add Header Text On Top Of the All Files Index

**Comment by CodeingBoy** [comment]
> Hello, can you put this funtion on this script
> 
> https://www.jqueryscript.net/other/jQuery-Plugin-For-AdBlock-Detection-Adi-js.html

Adding adblock detection is unnecessary(since we have no ads) and this is your personal need. So I will not add this to public source.
If you need to add yourself, take a look at `App.vue`.

> And can you tell me how to add Header Text On Top Of the All Files Index

This feature is not supported now. So you have to hack on your own.
